version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "monday"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "npm"
    # Group all updates together
    groups:
      dependencies:
        patterns:
          - "*"
    # Set the version update strategy
    versioning-strategy: auto
    # Allow up to 10 open pull requests for dependencies
    open-pull-requests-limit: 10
    # Specify the target branch
    target-branch: "main"
    # Configure the commit message
    commit-message:
      prefix: "npm"
      include: "scope" 